sudo: required

language: python

services:
  - docker

before_install:
  - docker pull shinesolutions/the-works-buildenv

script:
  - docker run --rm --workdir /opt/workspace -v `pwd`:/opt/workspace -i -t shinesolutions/aem-platform-buildenv bash -c "make ci"
